In [25]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error , r2_score
import joblib

In [26]:
np.set_printoptions(suppress=True)

In [27]:
data = pd.read_csv("C:/Users/User/Desktop/winequality-red.csv")

In [28]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [29]:
data.shape

(1596, 12)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1596 entries, 0 to 1595
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1596 non-null   float64
 1   volatile acidity      1596 non-null   float64
 2   citric acid           1596 non-null   float64
 3   residual sugar        1596 non-null   float64
 4   chlorides             1596 non-null   float64
 5   free sulfur dioxide   1596 non-null   float64
 6   total sulfur dioxide  1596 non-null   float64
 7   density               1596 non-null   float64
 8   pH                    1596 non-null   float64
 9   sulphates             1596 non-null   float64
 10  alcohol               1596 non-null   float64
 11  quality               1596 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 149.8 KB


In [31]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1596.000000       1596.000000  1596.000000     1596.000000   
mean        8.314160          0.527954     0.270276        2.535558   
std         1.732203          0.179176     0.193894        1.405515   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.600000          1.580000     0.790000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1596.000000          1596.000000           1596.000000  1596.000000   
mean      0.087120            15.858396             46.382206     0.996744   
std       0.045251            10.460554             32.839138     0.001888   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996745   
75%       0.090000            21.000000             62.000000     0.997833   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1596.000000  1596.000000  1596.000000  1596.000000  
mean      3.311917     0.656385    10.421147     5.637218  
std       0.153346     0.163057     1.060371     0.807080  
min       2.860000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     1.980000    14.000000     8.000000

In [32]:
Y = data["quality"]
X = data.drop("quality",axis = 1)
Y.unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, 
                                                    test_size=0.2, 
                                                    random_state=38, 
                                                    stratify=Y)

In [34]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
943            10.2             0.440         0.58             4.1      0.092   
144             8.1             0.670         0.55             1.8      0.117   
16              8.5             0.280         0.56             1.8      0.092   
1208            6.6             0.440         0.15             2.1      0.076   
1058            9.1             0.400         0.50             1.8      0.071   
...             ...               ...          ...             ...        ...   
811            12.6             0.410         0.54             2.8      0.103   
1112            7.0             0.690         0.07             2.5      0.091   
938             9.9             0.270         0.49             5.0      0.082   
748             8.3             0.650         0.10             2.9      0.089   
729             7.3             0.835         0.03             2.1      0.092   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
943                  11.0                  24.0  0.99745  3.29       0.99   
144                  32.0                 141.0  0.99680  3.17       0.62   
16                   35.0                 103.0  0.99690  3.30       0.75   
1208                 22.0                  53.0  0.99570  3.32       0.62   
1058                  7.0                  16.0  0.99462  3.21       0.69   
...                   ...                   ...      ...   ...        ...   
811                  19.0                  41.0  0.99939  3.21       0.76   
1112                 15.0                  21.0  0.99572  3.38       0.60   
938                   9.0                  17.0  0.99484  3.19       0.52   
748                  17.0                  40.0  0.99803  3.29       0.55   
729                  10.0                  19.0  0.99660  3.39       0.47   

      alcohol  
943      12.0  
144       9.4  
16       10.5  
1208      9.3  
1058     12.5  
...       ...  
811      11.3  
1112     11.3  
938      12.5  
748       9.5  
729       9.6  

[1276 rows x 11 columns]

In [35]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
376            11.4             0.625         0.66             6.2      0.088   
427            12.8             0.840         0.63             2.4      0.088   
158             7.6             0.950         0.03             2.0      0.090   
564             8.7             0.700         0.24             2.5      0.226   
1303            9.7             0.690         0.32             2.5      0.088   
...             ...               ...          ...             ...        ...   
522             9.2             0.430         0.49             2.4      0.086   
1278            7.1             0.460         0.20             1.9      0.077   
902             9.2             0.580         0.20             3.0      0.081   
54              7.6             0.510         0.15             2.8      0.110   
633             8.7             0.840         0.00             1.4      0.065   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
376                   6.0                  24.0   0.9988  3.11       0.99   
427                  13.0                  35.0   0.9997  3.10       0.60   
158                   7.0                  20.0   0.9959  3.20       0.56   
564                   5.0                  15.0   0.9991  3.32       0.60   
1303                 22.0                  91.0   0.9979  3.29       0.62   
...                   ...                   ...      ...   ...        ...   
522                  23.0                 116.0   0.9976  3.23       0.64   
1278                 28.0                  54.0   0.9956  3.37       0.64   
902                  15.0                 115.0   0.9980  3.23       0.59   
54                   33.0                  73.0   0.9955  3.17       0.63   
633                  24.0                  33.0   0.9954  3.27       0.55   

      alcohol  
376      13.3  
427      10.4  
158       9.6  
564       9.0  
1303     10.1  
...       ...  
522       9.5  
1278     10.4  
902       9.5  
54       10.2  
633       9.7  

[320 rows x 11 columns]

In [36]:
X_train_scaled = preprocessing.scale(X_train)
print( X_train_scaled )

[[ 1.11195387 -0.48719061  1.6118231  ... -0.16689871  1.98034594
   1.5045866 ]
 [-0.11009173  0.82227638  1.45595843 ... -0.9427193  -0.23914587
  -0.95131328]
 [ 0.12267886 -1.39812418  1.50791332 ... -0.10224699  0.54067558
   0.08772129]
 ...
 [ 0.93737593 -1.45505752  1.14422909 ... -0.81341587 -0.83900852
   1.97687504]
 [ 0.00629356  0.70840969 -0.88201162 ... -0.16689871 -0.65904973
  -0.85685559]
 [-0.57563292  1.76167662 -1.24569585 ...  0.47961845 -1.13893985
  -0.7623979 ]]


In [37]:
print( X_train_scaled.mean(axis=0) )
print( X_train_scaled.std(axis=0) )

[ 0. -0. -0.  0.  0. -0. -0. -0.  0.  0. -0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [40]:
X_train_scaled = scaler.transform(X_train)
print (X_train_scaled.mean(axis=0))
print (X_train_scaled.std(axis=0))

[ 0. -0. -0.  0.  0. -0. -0. -0.  0.  0. -0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [41]:
X_test_scaled = scaler.transform(X_test)
print (X_test_scaled.mean(axis=0))

[ 0.0724877   0.06764265  0.01323608  0.01075375 -0.03607542 -0.00626225
 -0.06727066 -0.02721265 -0.12568324 -0.10417677  0.06602554]


In [43]:
pipeline = make_pipeline(preprocessing.StandardScaler(),
                         RandomForestRegressor(n_estimators=100,
                                               random_state=46))

In [44]:
print( pipeline.get_params() )

{'memory': None, 'steps': [('standardscaler', StandardScaler()), ('randomforestregressor', RandomForestRegressor(random_state=46))], 'verbose': False, 'standardscaler': StandardScaler(), 'randomforestregressor': RandomForestRegressor(random_state=46), 'standardscaler__copy': True, 'standardscaler__with_mean': True, 'standardscaler__with_std': True, 'randomforestregressor__bootstrap': True, 'randomforestregressor__ccp_alpha': 0.0, 'randomforestregressor__criterion': 'squared_error', 'randomforestregressor__max_depth': None, 'randomforestregressor__max_features': 'auto', 'randomforestregressor__max_leaf_nodes': None, 'randomforestregressor__max_samples': None, 'randomforestregressor__min_impurity_decrease': 0.0, 'randomforestregressor__min_samples_leaf': 1, 'randomforestregressor__min_samples_split': 2, 'randomforestregressor__min_weight_fraction_leaf': 0.0, 'randomforestregressor__n_estimators': 100, 'randomforestregressor__n_jobs': None, 'randomforestregressor__oob_score': False, 'rand

In [45]:
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [47]:
clf = GridSearchCV(pipeline, hyperparameters, cv=10) 
clf.fit(X_train,Y_train)

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('randomforestregressor',
                                        RandomForestRegressor(random_state=46))]),
             param_grid={'randomforestregressor__max_depth': [None, 5, 3, 1],
                         'randomforestregressor__max_features': ['auto', 'sqrt',
                                                                 'log2']})

In [49]:
pred = clf.predict(X_test)
print( r2_score(Y_test, pred) )
print( mean_squared_error(Y_test, pred) )

0.547841681093666
0.2958634375


In [50]:
joblib.dump(clf, 'rf_regressor.pkl')

['rf_regressor.pkl']